name: Deploy all of the sessions

on:
  push:
    branches: [main]

jobs:
  package_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate a static website for each session
        run: make package
      - name: Deploy website to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/static_website
